name: janus-gateway
base: core18
summary: Janus WebRTC Server
adopt-info: janus
description: |
  Janus is an open source, general purpose, WebRTC server designed and developed by Meetecho.
license: GPL-3.0
grade: devel
confinement: strict
architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: armhf
layout:
  /opt/janus/lib/janus:
    bind: $SNAP/opt/janus/lib/janus
  /opt/janus/share/janus/streams:
    bind: $SNAP/opt/janus/share/janus/streams
  /opt/janus/etc/janus:
    bind: $SNAP_COMMON/etc
  /opt/janus/share/janus/recordings:
    bind: $SNAP_COMMON/share/recordings
  /opt/janus/share/janus/demos/voicemail:
    bind: $SNAP_COMMON/share/voicemail
parts:
  lws:
    plugin: cmake
    source-type: git
    source: https://github.com/warmcat/libwebsockets.git
    source-branch: v3.2-stable
    configflags:
      - -DLWS_WITHOUT_TESTAPPS=ON
    build-packages:
      - libssl-dev
    stage-packages:
      - libssl1.1
  nice:
    plugin: autotools
    source-type: git
    source: https://gitlab.freedesktop.org/libnice/libnice
    source-tag: 0.1.17
    build-packages:
      - pkg-config
      - libglib2.0-dev
      - gtk-doc-tools
  usrsctp:
    plugin: autotools
    source-type: git
    source: https://github.com/sctplab/usrsctp.git
    configflags:
      - --prefix=/usr
  libsrtp:
    plugin: autotools
    source-type: git
    source: https://github.com/cisco/libsrtp.git
    source-tag: v2.3.0
    configflags:
      - --prefix=/usr
      - --enable-openssl
  mqtt:
    plugin: cmake
    source-type: git
    source: https://github.com/eclipse/paho.mqtt.c.git
    source-tag: v1.3.8
    configflags:
      - -DPAHO_BUILD_SHARED=FALSE
      - -DPAHO_BUILD_STATIC=TRUE
      - -DPAHO_WITH_SSL=TRUE
      - -DPAHO_ENABLE_TESTING=FALSE
      - -DPAHO_ENABLE_CPACK=FALSE
  janus:
    plugin: autotools
    source-type: git
    source: https://github.com/meetecho/janus-gateway.git
    override-pull: |
        snapcraftctl pull
        snapcraftctl set-version "$(git describe)"
    configflags:
      - --prefix=/opt/janus
      - --enable-post-processing
    after:
      - lws
      - nice
      - usrsctp
      - libsrtp
      - mqtt
    build-packages:
      - g++
      - make
      - libmicrohttpd-dev
      - libjansson-dev
      - libssl-dev
      - libsofia-sip-ua-dev
      - libglib2.0-dev
      - libopus-dev
      - libogg-dev
      - libcurl4-openssl-dev
      - liblua5.3-dev
      - libconfig-dev
      - libavutil-dev
      - libavcodec-dev
      - libavformat-dev
      - pkg-config
      - gengetopt
      - libtool
      - automake
    stage-packages:
      - libconfig9
      - libjansson4
      - libcurl4
      - libogg0
      - libmicrohttpd12
      - libopus0
      - libsofia-sip-ua0
      - libavutil55
      - libavcodec57
      - libavformat57

apps:
  janus-gateway:
    command: opt/janus/bin/janus -o
    daemon: simple
    plugs:
      - network-bind
      - network
  janus-pp-rec:
    command: opt/janus/bin/janus-pp-rec
