name: janus-gateway
base: core22
summary: Janus WebRTC Server
adopt-info: janus
description: |
  Janus is an open source, general purpose, WebRTC server designed and developed by Meetecho.
  
  **Config files location:** /var/snap/janus-gateway/common/etc ($SNAP_COMMON/etc)
license: GPL-3.0
grade: devel
confinement: strict
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64
layout:
  /opt/janus/lib/janus:
    bind: $SNAP/opt/janus/lib/janus
  /opt/janus/share/janus/streams:
    bind: $SNAP/opt/janus/share/janus/streams
  /opt/janus/etc/janus:
    bind: $SNAP_COMMON/etc
  /opt/janus/share/janus/recordings:
    bind: $SNAP_COMMON/share/recordings
  /opt/janus/share/janus/demos/voicemail:
    bind: $SNAP_COMMON/share/voicemail
parts:
  meson-deps:
    plugin: nil
    override-build: |
      pip install meson
    build-packages:
      - python3-pip
  lws:
    plugin: cmake
    source-type: git
    source: https://github.com/warmcat/libwebsockets.git
    source-branch: v4.3-stable
    cmake-parameters:
      - -DLWS_WITHOUT_TESTAPPS=ON
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DLWS_MAX_SMP=1
      - -DLWS_WITHOUT_EXTENSIONS=0
      - -DCMAKE_C_FLAGS="-fpic"
    build-packages:
      - libssl-dev
      - libglib2.0-dev
    stage-packages:
      - libssl3
  nice:
    plugin: meson
    source-type: git
    source: https://github.com/libnice/libnice.git
    source-branch: latest-release
    after:
      - meson-deps
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - pkg-config
      - libglib2.0-dev
      - gtk-doc-tools
      - ninja-build
  usrsctp:
    plugin: autotools
    source-type: git
    source: https://github.com/sctplab/usrsctp.git
    source-tag: 0.9.5.0
    autotools-configure-parameters:
      - --prefix=/usr
  libsrtp:
    plugin: autotools
    source-type: git
    source: https://github.com/cisco/libsrtp.git
    source-tag: v2.5.0
    autotools-configure-parameters:
      - --prefix=/usr
      - --enable-openssl
  mqtt:
    plugin: cmake
    source-type: git
    source: https://github.com/eclipse/paho.mqtt.c.git
    source-tag: v1.3.13
    cmake-parameters:
      - -DPAHO_BUILD_SHARED=FALSE
      - -DPAHO_BUILD_STATIC=TRUE
      - -DPAHO_WITH_SSL=TRUE
      - -DPAHO_ENABLE_TESTING=FALSE
      - -DPAHO_ENABLE_CPACK=FALSE
      - -DCMAKE_INSTALL_PREFIX=/usr
  janus:
    plugin: autotools
    source-type: git
    source: https://github.com/meetecho/janus-gateway.git
    build-environment:
      - CFLAGS: "${CFLAGS:+$CFLAGS} -O1 -g3 -ggdb3 -fno-omit-frame-pointer -fsanitize=address"
      - LDFLAGS: "${LDFLAGS:+$LDFLAGS} -fsanitize=address"
    override-pull: |
        craftctl default
        craftctl set version="$(git describe)"
    autotools-configure-parameters:
      - --prefix=/opt/janus
      - --enable-post-processing
    after:
      - lws
      - nice
      - usrsctp
      - libsrtp
      - mqtt
    build-packages:
      - g++
      - make
      - libmicrohttpd-dev
      - libjansson-dev
      - libssl-dev
      - libsofia-sip-ua-dev
      - libglib2.0-dev
      - libopus-dev
      - libogg-dev
      - libcurl4-openssl-dev
      - liblua5.3-dev
      - libconfig-dev
      - libavutil-dev
      - libavcodec-dev
      - libavformat-dev
      - librabbitmq-dev
      - pkg-config
      - gengetopt
      - libtool
      - automake
    stage-packages:
      - libconfig9
      - libjansson4
      - libcurl4
      - libogg0
      - libmicrohttpd12
      - libopus0
      - libsofia-sip-ua0
      - libavutil56
      - libavcodec58
      - libavformat58
      - librabbitmq4
      - libpcap0.8
      - libasan6

apps:
  janus-gateway:
    command: opt/janus/bin/janus -o
    daemon: simple
    plugs:
      - network-bind
      - network
  janus-pp-rec:
    command: opt/janus/bin/janus-pp-rec
