name: nightly-build
on:
  schedule:
    - cron: "15 4 * * *"
jobs:
  trigger-snapcraft-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: trigger-build
      - name: Log current date and time
        run: echo `date` >> trigger-build.txt
      - name: Commit changes
        run: |
          git config --local user.email "rsatom@users.noreply.github.com"
          git config --local user.name "Github Action"
          git add ./trigger-build.txt
          git commit -m "trigger build"
      - name: Push changes
        run: |
          git push "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:trigger-build

